/* wc_cn_20.h — Work Companion Chinese font (simhei 20px, bpp2, 157 CJK glyphs + ASCII).
 * Generated by lv_font_conv via tools/gen_font.py; regenerate when UI text changes. */
#pragma once
#include "lvgl.h"

LV_FONT_DECLARE(wc_cn_20);
